api_platform:
    title: Quira API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    eager_loading:
        max_joins: 60 
        force_eager: false
    defaults:
        stateless: true
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 100
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
