doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    # MySQL puede hacer "implicit commits" en ciertas operaciones DDL; evita warnings y estados confusos
    transactional: false
    enable_profiler: false
